[package]
name = "jjvm"
version = "0.1.0"
authors = ["OisinA"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
jjvm_loader = { path = "../jjvm_loader" }
jjvm_vm = { path = "../jjvm_vm" }